name: GitHub Action flow to Docker GitHub

on:
    push:
        branches: [main]
        
jobs:
    build-push-images:
        name: Budowa i publikacja obrazów w repozytorium
        runs-on: ubuntu:latest
        
    steps:
        
        -name: Checkout code
            uses: actions/checkout@v2
        
        -name: Buildx set-up
            id: buildx
            uses: docker/setup-buildx-action@v1
            
        -name: Login to DockerHub
            uses: docker/login-action@v1
            with:
                username: ${{secrets.DOCKER_HUB-USERNAME}}
                password: ${{secrets.DOCKER_HUB_ACCESS_TOKEN}}
                
        -name: Build and push
            id: docker_build
            uses: docker/build-push-action@v2
            with:
                context: ./
                file: ./dockerfile.v1
                push: true
                tags: weronika135/lab6
                
        -name: Image digest
            run: echo ${{steps.docker_build.outputs.digest}}
